config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('welcome')

  get 'welcome', to: 'pages#index', as: 'welcome_page'
  post '/upload', to: 'pages#create'

  get 'ror', to: 'pages#ror', as: 'ror_page'
  get 'about', to: 'pages#about', as: 'about_page'
  get 'fuzzing', to: 'pages#fuzzing', as: 'fuzzing_page'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  has_many(
    :blog_posts,
    class_name: 'BlogPost',
    foreign_key: 'user_id',
    inverse_of: :author
  )

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    ALLOWED_IMAGE_EXTENSIONS = %w[jpg jpeg gif png bmp].freeze

    def index
        render :welcome
    end

    def create
        uploaded_file = params[:file_upload]
        
        if uploaded_file && image_extension_allowed?(uploaded_file.original_filename)
        dir = Rails.root.join('public', 'uploads')
        FileUtils.mkdir_p(dir) unless Dir.exist?(dir)
        
        file_path = dir.join(uploaded_file.original_filename)
        
        File.open(file_path, 'wb') do |file|
            file.write(uploaded_file.read)
        end
        
        # Redirect with a success message only if the file is allowed and saved
        redirect_to welcome_page_path, notice: "File uploaded successfully."
        else
        # If the file is not allowed, redirect with an error message
        redirect_to welcome_page_path, alert: "File type not allowed."
        end
        
        rescue StandardError => e
            redirect_to welcome_page_path, alert: "File upload failed: #{e.message}"
    end

    def ror
        render :ror
    end

    def about
        render :about
    end

    def fuzzing
        render :fuzzing
    end

    def image_extension_allowed?(filename)
        extension = File.extname(filename).delete('.').downcase
        ALLOWED_IMAGE_EXTENSIONS.include?(extension)
    end


end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  BOOTSTRAP_ALERT_CLASS = {
    'success' => 'alert-success',
    'error'   => 'alert-danger',
    'notice'  => 'alert-info',
    'alert'   => 'alert-danger',
    'warn'    => 'alert-warning'
  }.freeze

  def alert_class(flash_key)
    BOOTSTRAP_ALERT_CLASS.fetch(flash_key, 'alert-info')
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_sidebar.html.erb
<!-- app/views/layouts/_sidebar.html.erb -->

<div class="sidebar">
    <%= link_to 'Home', welcome_page_path %>
    <%= link_to 'Ruby on Rails', ror_page_path %>
    <%= link_to 'Fuzzing', fuzzing_page_path %>
    <%= link_to 'About', about_page_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <div class="container text-end my-1">
    <% if user_signed_in? %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-outline-primary btn-sm'  %>
    <% else %>
      <%= link_to 'Admin Sign In', new_user_session_path, class: 'btn btn-primary btn-sm' %>
    <% end %>
    </div>
    <%= render 'shared/flash' %>

    <main role="main" class="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <div style="text-align: center;">
        <img src="<%= asset_path('academic2.png') %>" alt="Image">
    </div>
    <p>
        This is a simple web application built with Ruby on Rails. It demonstrates how to create a basic website with multiple pages and a shared layout. The application includes pages for learning about Ruby on Rails, fuzzing, and other topics related to software development and cybersecurity.
    </p>
    </p>
    
    <h2>Features</h2>
    <ul>
        <li>Home page with information about the web application</li>
        <li>Pages for learning about Ruby on Rails, fuzzing, and other topics</li>
        <li>Shared layout with a sidebar for easy navigation</li>
        <li>Responsive design for mobile and desktop devices</li>
    </ul>
</body>
</html>

app/views/pages/fuzzing.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>What is Fuzzing?</title>
</head>
<body>
    <h1>What is Fuzzing?</h1>
    <p>
        Fuzzing is a software testing technique used to discover vulnerabilities in applications by providing invalid, unexpected, or random data as inputs. It aims to identify security flaws, such as buffer overflows, format string vulnerabilities, and injection attacks.
    </p>

    <h2>How Fuzzing Works</h2>
    <p>
        Fuzzing involves generating a large number of test inputs and feeding them into the target application. These inputs can be mutated or modified to include unexpected or malicious data. The goal is to trigger unexpected behavior or crashes in the application, which may indicate the presence of vulnerabilities.
    </p>

    <h2>Benefits of Fuzzing</h2>
    <p>
        Fuzzing is an effective technique for identifying security vulnerabilities because it can uncover unknown or unexplored attack vectors. It can be used to test various types of software, including web applications, network protocols, file formats, and more. By finding and fixing vulnerabilities early in the development process, organizations can enhance the security and reliability of their software.
    </p>

    <h2>Using Fuzzing in Cybersecurity</h2>
    <p>
        In cybersecurity, fuzzing is commonly used to assess the security of software applications. It helps identify vulnerabilities that could be exploited by attackers to gain unauthorized access, execute arbitrary code, or cause denial-of-service conditions. Fuzzing can be integrated into the software development lifecycle to ensure that applications are robust and resilient against potential attacks.
    </p>
</body>
</html>

app/views/pages/ror.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>What is Ruby on Rails?</title>
</head>
<body>
    <h1>What is Ruby on Rails?</h1>
    <p>Ruby on Rails is a web development framework that allows you to build powerful and scalable web applications with ease.</p>
    <p>It follows the Model-View-Controller (MVC) architectural pattern, which promotes separation of concerns and code organization.</p>
    <p>With Ruby on Rails, you can quickly prototype and build web applications, thanks to its convention-over-configuration approach.</p>
    <p>Whether you're a beginner or an experienced developer, Ruby on Rails provides a productive and enjoyable development experience.</p>
</body>
</html>

app/views/pages/welcome.html.erb
<h1 class="my-4">Welcome to the Webapp!</h1>

<div class="table-responsive">

  <p>This is an example of a website that uses a built-in user authentication system.</p>
  <p>You can view all of the main pages, but there are some pages that are only accessible to the admins of the website. This website was put together using Ruby on Rails and is used to demonstrate the powers of fuzzing and how it can be used to find vulnerabilities in a website.</p>
<form action="/upload" method="post" enctype="multipart/form-data">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="file" name="file_upload" accept="image/jpg, image/jpeg, image/png, image/gif, image/bmp">
  <button type="submit">Upload</button>
</form>

</div>

<%# accept="image/jpg, image/jpeg, image/png, image/gif, image/bmp" %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>